@base = http://localhost:8081/api
@id = a24a5213-ee44-439c-904f-7ea579be029e

POST {{base}}/users
Content-Type: application/json

{
    "name": "itallo",
    "email": "itallo@email.com",
    "password": "123456",
    "confirm_password": "123456"
}

###

GET {{base}}/users/{{id}}
