@base = http://localhost:8081/api
@id = a24a5213-ee44-439c-904f-7ea579be029e
@email = itallo@email.com

POST {{base}}/users
Content-Type: application/json

{
    "name": "icaro",
    "email":  "icaro@email.com",
    "password": "123456",
    "confirm_password": "123456"
}

###

GET {{base}}/users/{{id}}

###

GET {{base}}/users/email/{{email}}

###

GET {{base}}/users?search=
